Settings:
  authServer: "lobby"
  mainServer: "lobby"
msg:
  base:
    prefix: "§9[§3Login§9]> §2"
    error: "§9[§4Login§9]> §c"
    no_permissions: "§4ERROR §9§l> §r§bYou don't have permission to do that!"
    command_use: "§9[§4Login§9]> §r§cCommand use: §6$command"
  info:
    notAllowedCrackedUser: "Invalid username."
    pluginDisableKickMsg: "You have been disconnected \n Proxy restarting"
    successfulConnection: "The player $player is connected"
    authServerDown: "The authenticator server is down. \n sPlease tell the server administrator"
  adminCommands:
    pluginDisable: "The plugin is now disabled!"
    pluginEnable: "The plugin is now enabled!"
    playerAddedToAllowedCrackedList: "$player is now allowed to used a non official version"
    playerRemovedFromAllowedCrackedList: "$player is no longer allowed to used a non official version"
    listAllowedPlayers: "The allowed players are : "
  invalidPlayer:
    tooLongPassword: "$player has a too long name"
    invalidCharacter: "$player contains an invalid character"
allowedIPs: